/*nome: ammdb, user: giorgia, password: gio*/
CREATE TABLE utente(

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80),
    cognome VARCHAR(80),
    dataNascita DATE,
    email VARCHAR(80),
    password VARCHAR(80),
    frasePresentazione VARCHAR(404),
    tipoUtente VARCHAR(20),
    urlFoto VARCHAR(404)
);

CREATE TABLE post(

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    testo VARCHAR(404),
    urlImmagine VARCHAR(404),
    urlLink VARCHAR(404),
    idUtente INTEGER,
    FOREIGN KEY (idUtente) REFERENCES utente(id) ON DELETE CASCADE,
    bachecaUtente INTEGER,
    bachecaGruppo INTEGER
);

CREATE TABLE gruppo(

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(170),
    urlFoto VARCHAR(404),
    frase VARCHAR(404),
    adminG INTEGER,
    FOREIGN KEY(adminG) REFERENCES utente(id) ON DELETE CASCADE
);

	
CREATE TABLE appartenenza (

    id_utente INTEGER,
    id_gruppo INTEGER,
    data_iscrizione DATE,
    PRIMARY KEY (id_utente, id_gruppo),
    FOREIGN KEY (id_utente) REFERENCES utente(id) ON DELETE CASCADE, 
    FOREIGN KEY (id_gruppo) REFERENCES gruppo(id) ON DELETE CASCADE
);	

CREATE TABLE amicizia(

    id_ut1 INTEGER,
    id_ut2 INTEGER,
    data_stretta DATE,
    PRIMARY KEY (id_ut1, id_ut2),
    FOREIGN KEY (id_ut1) REFERENCES utente(id) ON DELETE CASCADE,
    FOREIGN KEY (id_ut2) REFERENCES utente(id) ON DELETE CASCADE
);

INSERT INTO utente (id, nome, cognome, dataNascita, email, password, frasePresentazione, tipoUtente, urlFoto)
VALUES (default, 'Violet', 'Baudelaire', '2000-12-25', 'violet1999@gmail.com', 'tredicipiudiciotto', 'Adoro costruire marchingegni. Hihi.', 'admin', 'M2/immagini/violet.jpg'), 
       (default, 'Sunny', 'Baudelaire', '2015-10-15', 'sunnnypaxxerella@gmail.com', '99scimmie', 'Levigare con i dentini: troppo figo.', 'normale', 'M2/immagini/sunny.jpg'), 
       (default, 'Klaus', 'Baudelaire', '2002-01-04', 'Klausssss23@gmail.com', 'ehiguys', 'Libri di giurisprudenza e cannocchiali sono il mio forte!', 'normale', 'M2/immagini/klaus.jpg' );

INSERT INTO post (id, testo, urlImmagine, urlLink, idutente, bachecaUtente, bachecaGruppo)
VALUES (default,'Il Conte avrà una sorpresina grazie alla mia nuova invenzione! Ahahah!', 'M3/immagini/olaf.jpg', '', 1 , 1, -1), 
       (default, 'Mi hanno appena regalato una trottola di legno, ma l ho mangiata!', '', '', 2, 2, -1), 
       (default, 'Questa è la brutta copia del mio cannocchiale speciale. #povery', '', 'https://it.wikipedia.org/wiki/Cannocchiale', 3, 3, -1), 
       (default, 'Ragazzi, sono veramente euforica!', '', '', 1, 1, -1);

INSERT INTO gruppo (id, nome, urlFoto, frase, adminG)
VALUES (default, 'Ignoranti disagiati', '', 'blablabla', 1), 
       (default, 'Sesi de Murera se...', '', 'Benvenuti nel paese dei pidanciuli!', 1), 
       (default, 'Fotografia', '', 'Siamo qui per criticarti.', 3);

INSERT INTO appartenenza (id_utente, id_gruppo, data_iscrizione)
VALUES (1, 1, '2016-10-16'),
       (1, 3, '2016-11-12'),
       (2, 1, '2016-04-22'), 
       (2, 2, '2016-09-30'), 
       (2, 3, '2017-01-01'),  
       (3, 2, '2017-02-02'), 
       (3, 3, '2017-02-15');

INSERT INTO amicizia (id_ut1, id_ut2, data_stretta)
VALUES (1, 2, '2016-11-14'),
       (1, 3, '2016-12-20'),
       (2, 1, '2016-11-14'),
       (3, 1, '2016-12-20');